### ISSUE TITLE
PNPM import error when starting dev server

### ISSUE THREAD

**Issue by Ziothh** [sofn-xyz/mailing#300] opened 2022-10-29 01:04 UTC
**Describe the bug**
When I run `npx mailing`I get this error:
> mailing linting templates in ./emails...
> event - compiled client and server successfully in 2.4s (179 modules)
> mailing watching for changes to emails
> mailing running preview at http://localhost:3883/
> wait  - compiling / (client and server)...
> warn  - ../node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib/index.js
> Module not found: Can't resolve 'encoding' in '/Users/digitalastronaut/Projects/learning/next-mailing/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib'
> error - Error: ENOENT: no such file or directory, open '../node_modules/.pnpm/uglify-js@3.17.4/node_modules/uglify-js/lib/utils.js'

**To Reproduce**
Running `npx mailing` when you have a NextJS app in the root folder with node_modules installed by PNPM

**Desktop (please complete the following information):**

- OS: MacOS Monterey

**Comment by psugihara** [comment] 2022-10-31 23:18
Hey @Ziothh, thanks for trying mailing and creating an issue! There are known issues with pnpm and yarn 3 (though I don't know root cause). Very happy to take outside PRs and setup e2e tests when we get it working but we haven't had time to prioritize yet since these package managers have relatively low usage.

**Comment by bebejane** [comment] 2022-11-05 10:38
Quick workaround to get rid of the errors 

pnpm i uglify-js encoding -D

Everything works with pnpm after installing these packages

**Comment by psugihara** [comment] 2022-11-05 16:27
Weird! I wonder why uglify-js isn't installed by the mjml dep in `mailing`'s  `package.json`.

I see this dependency chain in my yarn.lock
- mjml < mjml-cli < html-minifier < uglify-js

Not sure about encoding. I don't have that in my [yarn.lock](https://github.com/sofn-xyz/fynn-mailing/blob/main/yarn.lock).

**Comment by alexfarrill** [comment] 2022-11-29 16:59
Closing in favor of https://github.com/sofn-xyz/mailing/issues/381  Pull requests welcome!

**Closed by alexfarrill** 2022-11-29 16:59 UTC
Labels: bug, help wanted
