### ISSUE TITLE
.ts files stopped working

### ISSUE THREAD

**Issue by pstoica** [sofn-xyz/mailing#141] opened 2022-08-25 18:40 UTC
I have a couple of plain typescript files for images and theme tokens. I'm using `typescript: true`. `0.6.9` was working just fine, but something in `0.7.0` switched to start appending `.ts` to the variable name. Here's the syntax error:

```
import images.ts from "./emails/images.ts";
```

With this version I can no longer preview, build, or export.

**Comment by psugihara** [comment] 2022-08-25 18:43
aye, sorry @pstoica taking a look.

what file is that line in?

**Comment by pstoica** [comment] 2022-08-25 18:44
thank you! here's a more thorough stacktrace:

```
wait  - compiling / (client and server)...
error - ./src/moduleManifest.ts
Error: 
  x Expected ',', got '.'
   ,----
 3 | import images.ts from "./emails/images.ts";
   :              ^
   `----

Caused by:
    0: failed to process input file
    1: Syntax Error
wait  - compiling /_error (client and server)...
```

I haven't tried renaming the files or anything yet, I had to revert for now. let me know if it'd save you some effort.

**Comment by psugihara** [comment] 2022-08-25 18:46
gotcha, i think i see what the problem is. thanks for detail! will ping back in a bit when I think I have a fix.

**Comment by psugihara** [comment] 2022-08-25 18:57
hey @pstoica, can you try mailing@0.7.1-next.0 when you have a chance and let me know if it works for you?

**Comment by psugihara** [comment] 2022-08-25 18:59
scratch that hehe another sec.

**Comment by psugihara** [comment] 2022-08-25 19:20
OK, I repro'd what you were seeing and I believe it's fixed in #142 

Try out `mailing@0.7.1-next.2` to confirm. Thanks again!

**Comment by pstoica** [comment] 2022-08-25 19:34
it's closer! now the commands seem to have slightly different issues.

`build` is giving eslint errors. could it be due to my monorepo?
```shell
❯ yarn build
yarn run v1.19.0
$ mailing server build
mailing building .mailing...
info  - Checking validity of types  
warn  - The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config

Failed to compile.

./src/pages/api/render.ts
15:27  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any

./src/pages/index.tsx
1:23  Warning: 'useEffect' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Error: 'previews' is never reassigned. Use 'const' instead.  prefer-const
26:12  Warning: Fragments should contain more than one child - otherwise, there’s no need for a Fragment at all.  react/jsx-no-useless-fragment
62:19  Warning: The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
71:11  Warning: The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/pages/previews/[previewClass]/[previewFunction].tsx
1:30  Warning: 'useEffect' is defined but never used.  @typescript-eslint/no-unused-vars
6:26  Warning: 'NextPage' is defined but never used.  @typescript-eslint/no-unused-vars
66:12  Warning: Fragments should contain more than one child - otherwise, there’s no need for a Fragment at all.  react/jsx-no-useless-fragment

./src/components/Header.tsx
31:11  Warning: The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/HEAD/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/components/HotIFrame.tsx
27:11  Warning: <iframe> elements must have a unique title property.  jsx-a11y/iframe-has-title

./src/components/Intercept.tsx
13:12  Warning: Fragments should contain more than one child - otherwise, there’s no need for a Fragment at all.  react/jsx-no-useless-fragment

./src/components/PreviewSender.tsx
54:20  Warning: Fragments should contain more than one child - otherwise, there’s no need for a Fragment at all.  react/jsx-no-useless-fragment

./src/components/hooks/usePreviewHotkeys.tsx
18:64  Error: Missing semicolon.  semi

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
mailing server [subcommand]

build and start the mailing server

Options:
  --version     Show version number                     [boolean]
  --help        Show help                               [boolean]
  --subcommand  'build' or 'start', blank does both
  --emails-dir  the directory to look for your email templates in
                                        [default: "./src/emails"]
  --port        what port to start the preview server on
                                                  [default: 3883]
  --quiet                              [boolean] [default: false]

Error: Command failed: npx next build .mailing
    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at _callee$ (/Users/patrick/puzzle/frontend/node_modules/mailing/dist/mailing.cjs.dev.js:1662:29)
    at tryCatch (/Users/patrick/puzzle/frontend/node_modules/mailing/dist/mailing.cjs.dev.js:134:17)
    at Generator._invoke (/Users/patrick/puzzle/frontend/node_modules/mailing/dist/mailing.cjs.dev.js:114:24)
    at Generator.next (/Users/patrick/puzzle/frontend/node_modules/mailing/dist/mailing.cjs.dev.js:165:21)
    at asyncGeneratorStep (/Users/patrick/puzzle/frontend/node_modules/mailing/dist/mailing.cjs.dev.js:398:24)
    at _next (/Users/patrick/puzzle/frontend/node_modules/mailing/dist/mailing.cjs.dev.js:420:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 87383,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`preview` is looping on this:
```shell
TypeError: Cannot destructure property 'inAmpMode' of '(0 , _react).useContext(...)' as it is null.
    at Html (webpack-internal:///../../../node_modules/mailing/node_modules/next/dist/pages/_document.js:640:13)
    at renderWithHooks (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5661:16)
    at renderIndeterminateComponent (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5734:15)
    at renderElement (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5949:7)
    at renderNodeDestructiveImpl (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6079:14)
    at renderIndeterminateComponent (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5788:7)
    at renderElement (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:5949:7)
    at renderNodeDestructiveImpl (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6107:11)
    at renderNodeDestructive (/Users/patrick/puzzle/frontend/node_modules/react-dom/cjs/react-dom-server-legacy.browser.development.js:6079:14)
```

and `export-previews` is still doing:
```
Error: previewServerConfig is undefined
```

**Comment by psugihara** [comment] 2022-08-25 20:59
mind trying one more 😅 

`mailing@0.7.1-next.4`

🤞

**Comment by pstoica** [comment] 2022-08-25 21:03
all three work perfectly! thanks for the quick fix!

**Comment by psugihara** [comment] 2022-08-25 21:08
😭 😭 😭 😭 !!! ❤️ 

awesome, will get this merged and released. thanks for your help debugging!

**Comment by psugihara** [comment] 2022-08-25 21:13
release in 0.7.1 

# ⚡

**Closed by psugihara** 2022-08-25 21:13 UTC
